config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true
  validates :comment, length: { minimum: 6,
    too_short: "comment too short!" }
  validates :movie_id, uniqueness: { scope: :list_id,
    message: "bookmark already exist!" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists =   List.all
  end

  def show
   @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list =  List.new(strong_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def strong_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container col-6">
<h1>New bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1581785735604-419514e6099e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>Save Any Kind of movies!</h1>
    <p>Movie for all, enjoy cinema!</p>
    <%= link_to "Create new list", new_list_path, class: "btn btn-ghost" %>
  </div>
</div>
<br>
<div class="container">
<div class="cards">
  <% @lists.each do |list| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <%= link_to list.name, list_path(list.id)%>
  </div>
  <% end %>
</div>
</div>

<%# <div class ="card-category", style ="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1535016120720-40c646be5580?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80)"> %>

app/views/lists/new.html.erb
<div class="container col-4">
<h1>Create new lists!</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>
<%= link_to "Home Page", root_path %>
</div>

app/views/lists/show.html.erb
<div class="container col-6">
<h1><%= @list.name %></h1>
<%= link_to "Home Page", root_path, class: "btn btn-primary" %>
<ul class = "list-group" >
<% @list.bookmarks.each do |bookmark| %>
<li class= "list-group-item">
<img src="<%= bookmark.movie.poster_url %>" alt="" height="300">
<br>quit
<%= bookmark.id %>
<%= bookmark.movie.title %>
<%= bookmark.comment %>
<%= link_to "Delete",
    bookmark_path(bookmark),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</li>
<hr>
<% end %>
</ul>
<%= link_to "New Bookmark", new_list_bookmark_path(@list) %>
</div>